name: Deploy to Render

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image to Render registry
        run: |
          docker build -t achu2002/comingle-client .
          docker tag achu2002/comingle-client:latest registry.render.com/my-account/comingle-client:latest
          docker push registry.render.com/my-account/comingle-client:latest

      - name: Deployed to Render registry successfully
        run: echo Built and pushed Docker image to Render registry successfully
